title = "Christians Blog"
baseURL = "https://uhl-steine-scherben.org/blog"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Christian Uhl"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Christian Uhl"
  favicon = ""
  site_logo = ""
  description = "Christian's writings"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  [[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/chrisuhl"
  [[params.ananke_socials]]
    name = "mastodon"
    url = "https://mastodon.social/@christianuhl"
  [[params.ananke_socials]]
    name = "rss"
    url = "index.xml"
  [[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/christian-uhl-957a61151"

