title = "Christians Blog"
baseURL = "https://uhl-steine-scherben.org/blog/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Christian Uhl"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"



[params]
  menu = ['main', 'tags']
  custom_css = ["custom.css"]
  text_color = ""
  author = "Christian Uhl"
  favicon = "favicon.ico"
  site_logo = ""
  description = "Christian's writings"
  body_classes = "avenir bg-near-white f5"
  post_content_classes = "avenir"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  [[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/chrisuhl"
  [[params.ananke_socials]]
    name = "mastodon"
    url = "https://hachyderm.io/@chrisuhl"
  [[params.ananke_socials]]
    name = "rss"
    url = "/blog/index.xml"
  [[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/christian-uhl-957a61151"
  [markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false


